const PORTFOLIO = [
  {
    "id": "GV-002",
    "name": "タイミー",
    "nameEn": "Timee",
    "sector": "HR Tech",
    "stage": "Seed",
    "teamSize": "500名+",
    "ceo": "小川 嶺",
    "summary": "スキマバイトマッチングで人手不足を解決",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "スキマバイト",
      "ギグワーク",
      "人材マッチング",
      "短期雇用"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://corp.timee.co.jp/recruit/",
    "founded_year": "2017",
    "latest_round": "IPO",
    "latest_round_date": "2024-07"
  },
  {
    "id": "GV-003",
    "name": "助太刀",
    "nameEn": "Sukedachi",
    "sector": "Construction Tech",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "我妻 陽一",
    "summary": "建設現場の人材課題をテクノロジーで解決",
    "hiringNeeds": "inactive",
    "growthChallenges": "建設業界の深耕",
    "keywords": [
      "建設",
      "人材",
      "マッチング",
      "給与",
      "現場DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://corp.suke-dachi.jp/recruit",
    "founded_year": "2017",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-004",
    "name": "フォトラクション",
    "nameEn": "Photoruction",
    "sector": "Construction Tech",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "中島 貴春",
    "summary": "建設現場のDXを写真・図面管理で推進",
    "hiringNeeds": "セールス",
    "growthChallenges": "エンタープライズ展開",
    "keywords": [
      "建設DX",
      "写真管理",
      "工程管理",
      "BIM"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.photoruction.com/recruit",
    "founded_year": "2016",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-005",
    "name": "Baseconnect",
    "nameEn": "Baseconnect",
    "sector": "Sales Tech",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "國重 侑輝",
    "summary": "企業DBで営業活動を効率化",
    "hiringNeeds": "inactive",
    "growthChallenges": "データ品質向上",
    "keywords": [
      "企業データベース",
      "営業リスト",
      "B2Bデータ",
      "リード生成"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://baseconnect.in/about/recruit",
    "founded_year": "2017",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-006",
    "name": "Autify",
    "nameEn": "Autify",
    "sector": "Dev Tools",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "近澤 良",
    "summary": "AIでソフトウェアテストを自動化",
    "hiringNeeds": "グローバルセールス",
    "growthChallenges": "グローバル展開",
    "keywords": [
      "テスト自動化",
      "QA",
      "ノーコード",
      "AI",
      "ソフトウェア品質"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://autify.com/ja/careers",
    "founded_year": "2016",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-007",
    "name": "Zenport",
    "nameEn": "Zenport",
    "sector": "Logistics Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "国際物流のクラウド最適化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "グローバル展開",
    "keywords": [
      "国際物流",
      "サプライチェーン",
      "貿易DX",
      "クラウド"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/zenport",
    "founded_year": "2017",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-008",
    "name": "シェルフィー",
    "nameEn": "Shelfy",
    "sector": "Construction Tech",
    "stage": "Seed",
    "teamSize": "11-50名",
    "ceo": "呂 俊輝（ロイ シュンキ）",
    "summary": "建設業界のITインフラを整える総合プラットフォーム",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "内装",
      "マッチング",
      "安全書類",
      "建設DX",
      "Greenfile.work"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.shelfy.co.jp/recruit",
    "founded_year": "2014",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-009",
    "name": "Good Moneyger (VESTA)",
    "nameEn": "Good Moneyger",
    "sector": "FinTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "清水 俊博",
    "summary": "運用しないロボアドバイザーで無料の投資アドバイス",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ロボアドバイザー",
      "投資信託",
      "AI",
      "資産運用",
      "楽天証券"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2017",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-010",
    "name": "JobRainbow",
    "nameEn": "JobRainbow",
    "sector": "HR Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "星 賢人",
    "summary": "ダイバーシティ採用を推進するプラットフォーム",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "D&I市場拡大",
    "keywords": [
      "LGBT",
      "ダイバーシティ",
      "採用",
      "インクルージョン"
    ],
    "target_market": "B2B2C",
    "target_segment": "SMB",
    "recruitUrl": "https://jobrainbow.jp/recruit",
    "founded_year": "2016",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-011",
    "name": "Docquity",
    "nameEn": "Docquity",
    "sector": "Health Tech",
    "stage": "Seed",
    "teamSize": "100-300名",
    "ceo": "Indranil Roychowdhury",
    "summary": "医師同士の知識共有で医療水準を向上",
    "hiringNeeds": "日本市場展開",
    "growthChallenges": "新市場参入",
    "keywords": [
      "医師",
      "SNS",
      "医療",
      "東南アジア",
      "CME"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://docquity.com/careers",
    "founded_year": "2015",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-012",
    "name": "Qoala",
    "nameEn": "Qoala",
    "sector": "InsurTech",
    "stage": "Seed",
    "teamSize": "100-300名",
    "ceo": "Harshet Lunani",
    "summary": "デジタル保険で東南アジアの保険普及を推進",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "東南アジア展開",
    "keywords": [
      "保険",
      "インシュアテック",
      "東南アジア",
      "デジタル"
    ],
    "target_market": "B2C",
    "target_segment": "SMB",
    "recruitUrl": "https://www.qoala.id/en/career",
    "founded_year": "2018",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-013",
    "name": "bobobox",
    "nameEn": "Bobobox",
    "sector": "Travel Tech",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "Indrayana Rustandi",
    "summary": "テクノロジーで宿泊体験を再定義",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "東南アジア展開",
    "keywords": [
      "カプセルホテル",
      "スマート宿泊",
      "インドネシア"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.linkedin.com/company/bfrfrrrobobox/jobs/",
    "founded_year": "2017",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-014",
    "name": "BlueBank",
    "nameEn": "BlueBank",
    "sector": "Fintech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "法人経営者向け会員制オーナーズアプリ（法人口座・ビジネスカード・資産管理）\n",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "SME市場拡大",
    "keywords": [
      "補助金",
      "助成金",
      "中小企業",
      "行政DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://herp.careers/v1/scheeme",
    "founded_year": "2019",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-015",
    "name": "テックドクター",
    "nameEn": "TechDoctor",
    "sector": "Health Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "湊 和修",
    "summary": "ウェアラブルデータで健康管理を革新",
    "hiringNeeds": "データサイエンティスト",
    "growthChallenges": "エビデンス構築",
    "keywords": [
      "デジタルヘルス",
      "ウェアラブル",
      "健康管理",
      "予防医療"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://www.technology-doctor.com/recruit",
    "founded_year": "2019",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-016",
    "name": "FastLabel",
    "nameEn": "FastLabel",
    "sector": "AI / ML",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "上田 英介",
    "summary": "AI開発を10倍速くするデータプラットフォーム",
    "hiringNeeds": "エンタープライズセールス",
    "growthChallenges": "大企業AI導入支援",
    "keywords": [
      "AI",
      "アノテーション",
      "教師データ",
      "MLOps",
      "データプラットフォーム"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://fastlabel.ai/careers",
    "founded_year": "2020",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-017",
    "name": "HOKUTO",
    "nameEn": "HOKUTO",
    "sector": "Health Tech",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "五十嵐 健祐",
    "summary": "エビデンスベースの臨床支援で医療を変革",
    "hiringNeeds": "コンテンツ, エンジニア",
    "growthChallenges": "コンテンツ拡充とマネタイズ",
    "keywords": [
      "臨床支援",
      "医師向けアプリ",
      "エビデンス",
      "医療情報"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.wantedly.com/companies/company_2277005",
    "founded_year": "2018",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-018",
    "name": "ROUTE06",
    "nameEn": "ROUTE06",
    "sector": "Enterprise DX",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "遠藤 崇史",
    "summary": "大企業のDXプラットフォーム構築を支援",
    "hiringNeeds": "エンジニア, PM",
    "growthChallenges": "エンタープライズ展開",
    "keywords": [
      "エンタープライズDX",
      "プラットフォーム構築",
      "デジタル変革"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://route06.co.jp/careers",
    "founded_year": "2020",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-019",
    "name": "Acall",
    "nameEn": "Acall",
    "sector": "PropTech",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "長沼 斉寿",
    "summary": "ハイブリッドワーク時代のオフィス管理を一元化",
    "hiringNeeds": "グローバルセールス",
    "growthChallenges": "グローバル展開（シンガポール）",
    "keywords": [
      "スマートオフィス",
      "受付",
      "会議室管理",
      "ハイブリッドワーク"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.acall.inc/recruit",
    "founded_year": "2015",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-021",
    "name": "Kamereo",
    "nameEn": "Kamereo",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "田中 卓",
    "summary": "飲食店の食材調達をデジタル化",
    "hiringNeeds": "オペレーション",
    "growthChallenges": "ベトナム全国展開",
    "keywords": [
      "食材調達",
      "B2B",
      "ベトナム",
      "飲食DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://kamereo.vn/tuyen-dung",
    "founded_year": "2018",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-022",
    "name": "BUYMED",
    "nameEn": "BUYMED",
    "sector": "Health Tech",
    "stage": "Seed",
    "teamSize": "100-300名",
    "ceo": "Peter Nguyen",
    "summary": "医薬品流通をデジタルで効率化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "ベトナム全国拡大",
    "keywords": [
      "医薬品",
      "B2B",
      "ベトナム",
      "流通DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://career.buymed.com/",
    "founded_year": "2018",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-023",
    "name": "Manabie",
    "nameEn": "Manabie",
    "sector": "EdTech",
    "stage": "Seed",
    "teamSize": "100-300名",
    "ceo": "本間 拓也",
    "summary": "東南アジアの教育格差をテクノロジーで解消",
    "hiringNeeds": "コンテンツ, エンジニア",
    "growthChallenges": "東南アジア拡大",
    "keywords": [
      "教育",
      "EdTech",
      "東南アジア",
      "ブレンデッドラーニング"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://manabie.com/careers",
    "founded_year": "2019",
    "latest_round": "Series B",
    "latest_round_date": ""
  },
  {
    "id": "GV-024",
    "name": "Sinbad",
    "nameEn": "Sinbad",
    "sector": "Retail Tech",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "不明",
    "summary": "インドネシアの小売流通をDXで効率化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "インドネシア拡大",
    "keywords": [
      "B2B EC",
      "小売",
      "FMCG",
      "インドネシア"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2018",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-025",
    "name": "Microverse",
    "nameEn": "Microverse",
    "sector": "Entertainment Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "IP×Web3で新しいコンテンツ経済圏を創出",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "Web3市場開拓",
    "keywords": [
      "NFT",
      "Web3",
      "IP",
      "コンテンツ",
      "マネタイズ"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2020",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-026",
    "name": "Oyraa",
    "nameEn": "Oyraa",
    "sector": "HR Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "必要な時にすぐ通訳を手配",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "グローバル展開",
    "keywords": [
      "通訳",
      "マッチング",
      "多言語",
      "リアルタイム"
    ],
    "target_market": "B2C",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2018",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-027",
    "name": "Petokoto",
    "nameEn": "PETOKOTO",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "大久保 泰介",
    "summary": "ペットの健康をフレッシュフードで支える",
    "hiringNeeds": "マーケティング",
    "growthChallenges": "ブランド拡大",
    "keywords": [
      "ペットフード",
      "フレッシュフード",
      "D2C",
      "ペットメディア"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.wantedly.com/companies/petokoto",
    "founded_year": "2017",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-028",
    "name": "funfo",
    "nameEn": "funfo",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "飲食店のDXをモバイルオーダーで推進",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "飲食チェーン展開",
    "keywords": [
      "モバイルオーダー",
      "飲食DX",
      "店舗DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://funfo.co.jp/recruit",
    "founded_year": "2019",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-029",
    "name": "GAXI",
    "nameEn": "GAXI",
    "sector": "EdTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "松原 良輔",
    "summary": "奨学金を変え、運命を変え、社会を変える",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "学生基盤拡大",
    "keywords": [
      "奨学金",
      "教育",
      "マッチング",
      "給付型"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://gaxi.co.jp/recruit",
    "founded_year": "2020",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-030",
    "name": "Malme",
    "nameEn": "Malme",
    "sector": "Construction Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "土木設計をAIで革新",
    "hiringNeeds": "AIエンジニア",
    "growthChallenges": "プロダクト開発",
    "keywords": [
      "土木DX",
      "AI設計",
      "インフラ",
      "Structural Engine"
    ],
    "target_market": "B2C",
    "target_segment": "SMB",
    "recruitUrl": "https://www.malme.net/recruit",
    "founded_year": "2020",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-031",
    "name": "UMAMI UNITED",
    "nameEn": "UMAMI UNITED",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "日本発の植物性代替卵で食の未来を創る",
    "hiringNeeds": "R&D, 海外営業",
    "growthChallenges": "海外展開（米国・欧州）",
    "keywords": [
      "代替卵",
      "植物性",
      "フードテック",
      "サステナブル"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2020",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-032",
    "name": "RePlayce",
    "nameEn": "RePlayce",
    "sector": "EdTech",
    "stage": "Series A",
    "teamSize": "10-30名",
    "ceo": "山本 将裕",
    "summary": "中高生と社会をつなぐ探究型キャリア教育",
    "hiringNeeds": "キャリアコーチ, エンジニア, 教育プログラム開発",
    "growthChallenges": "教育機関ネットワーク拡大",
    "keywords": [
      "キャリア教育",
      "探究学習",
      "中高生",
      "通信制高校",
      "はたらく部"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://replayce.co.jp/recruit",
    "founded_year": "2024",
    "latest_round": "Series A",
    "latest_round_date": "2025-10"
  },
  {
    "id": "GV-033",
    "name": "モカブル",
    "nameEn": "Mokable",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "1-10名",
    "ceo": "糸山 彰徳",
    "summary": "コーヒーを「飲む」から「食べる」へ革新",
    "hiringNeeds": "R&D, 海外営業, マーケティング",
    "growthChallenges": "北米展開・ブランド構築",
    "keywords": [
      "食べるコーヒー",
      "フードテック",
      "サステナブル",
      "カーブアウト",
      "サントリー"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://mokable.jp/careers",
    "founded_year": "2025",
    "latest_round": "Seed",
    "latest_round_date": "2025-10"
  },
  {
    "id": "GV-034",
    "name": "Al Travel",
    "nameEn": "Al Travel",
    "sector": "Travel Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "出張手配をクラウドで効率化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "エンタープライズ展開",
    "keywords": [
      "出張管理",
      "クラウド",
      "BTM",
      "旅行DX"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2021",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-035",
    "name": "Liberont",
    "nameEn": "Liberont",
    "sector": "Retail Tech",
    "stage": "Seed",
    "teamSize": "1-10名",
    "ceo": "大河 淳司, 小島 剛",
    "summary": "バイバック保証で新しい購買体験を創出",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "バイバック保証",
      "Buy Now Sell Later",
      "EC",
      "サーキュラー"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://liberont.com/career",
    "founded_year": "2024",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-036",
    "name": "nonat",
    "nameEn": "nonat",
    "sector": "Health Tech",
    "stage": "Pre-Series A",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "周産期医療をAIで革新",
    "hiringNeeds": "AIリサーチャー",
    "growthChallenges": "データ収集・研究開発",
    "keywords": [
      "医療AI",
      "周産期",
      "早産",
      "基盤モデル",
      "女性健康"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2021",
    "latest_round": "Pre-Series A",
    "latest_round_date": "2025"
  },
  {
    "id": "GV-037",
    "name": "amoibe",
    "nameEn": "amoibe",
    "sector": "EdTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "新庄 隼人",
    "summary": "AI時代のエンジニア育成を変革",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "大手SIer開拓",
    "keywords": [
      "エンジニア研修",
      "リスキリング",
      "AI人材",
      "OJT",
      "SIer"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://amoibe.co.jp/recruit",
    "founded_year": "2014",
    "latest_round": "Seed",
    "latest_round_date": "2025"
  },
  {
    "id": "GV-038",
    "name": "シェルパ・アンド・カンパニー",
    "nameEn": "Cierpa & Company",
    "sector": "ESG / GovTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "杉本 淳",
    "summary": "ESG経営をクラウドで推進",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ESG",
      "サステナビリティ",
      "情報開示",
      "SmartESG"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://cierpa.co.jp/recruit",
    "founded_year": "2019",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-039",
    "name": "RemitAid",
    "nameEn": "RemitAid",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2019",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-040",
    "name": "Luxstay",
    "nameEn": "Luxstay",
    "sector": "Travel Tech",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "不明",
    "summary": "ベトナムの民泊市場をデジタル化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "ベトナム国内拡大",
    "keywords": [
      "民泊",
      "ベトナム",
      "旅行",
      "ホームステイ"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.linkedin.com/company/luxstay/jobs/",
    "founded_year": "2016",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-041",
    "name": "SPUN",
    "nameEn": "SPUN",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2021",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-042",
    "name": "BCFD Technologies",
    "nameEn": "BCFD Technologies",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2020",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-043",
    "name": "Kinish",
    "nameEn": "Kinish",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2020",
    "latest_round": "Angel/Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-044",
    "name": "Plutos ONE",
    "nameEn": "Plutos ONE",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "テクニカルサービスプロバイダー",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2020",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-045",
    "name": "Sports For Life (SFL)",
    "nameEn": "Sports For Life",
    "sector": "Sports Tech",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "インドのユーススポーツをスケール",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "インド拡大",
    "keywords": [
      "ユーススポーツ",
      "インド",
      "教育",
      "健康"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2020",
    "latest_round": "Series A",
    "latest_round_date": "2025-11"
  },
  {
    "id": "GV-046",
    "name": "AI Mage",
    "nameEn": "AI Mage",
    "sector": "AI / ML",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）AIイメージ生成関連",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "AI",
      "画像生成"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2022",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-047",
    "name": "NanoFrontier",
    "nameEn": "NanoFrontier",
    "sector": "DeepTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "井上 誠也",
    "summary": "有機ナノ粒子化技術で材料開発を革新",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ナノ粒子",
      "有機材料",
      "再沈殿法",
      "東北大学",
      "素材"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2025",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-048",
    "name": "Anaguma",
    "nameEn": "Anaguma",
    "sector": "",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2021",
    "latest_round": "Series A",
    "latest_round_date": "2025-07"
  },
  {
    "id": "GV-049",
    "name": "handpickd",
    "nameEn": "handpickd",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "インドの生鮮食品ECを変革",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "インド拡大",
    "keywords": [
      "生鮮食品",
      "EC",
      "インド"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2021",
    "latest_round": "",
    "latest_round_date": "2025-06"
  },
  {
    "id": "GV-050",
    "name": "ColorSing",
    "nameEn": "ColorSing",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査 - カンタさん関連スタートアップ）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2020",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-051",
    "name": "パートナープロップ",
    "nameEn": "Partner Prop",
    "sector": "Sales Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "井上 拓海",
    "summary": "パートナーマーケティングをSaaSで効率化",
    "hiringNeeds": "セールス, CS",
    "growthChallenges": "急成長フェーズ",
    "keywords": [
      "PRM",
      "パートナーマーケティング",
      "代理店管理",
      "SaaS"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.skygate-tech.com/recruit",
    "founded_year": "2023",
    "latest_round": "Series A",
    "latest_round_date": "2025"
  },
  {
    "id": "GV-052",
    "name": "Smart Craft",
    "nameEn": "Smart Craft",
    "sector": "Manufacturing Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "浮部 史也",
    "summary": "製造現場のDXプラットフォーム",
    "hiringNeeds": "エンジニア, セールス",
    "growthChallenges": "製造業市場開拓",
    "keywords": [
      "製造DX",
      "工場",
      "IoT",
      "生産管理",
      "スマホ"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://smartcraft.jp/recruit",
    "founded_year": "2020",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-053",
    "name": "ユアトレード",
    "nameEn": "YourTrade",
    "sector": "Logistics Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "德永 翔平",
    "summary": "越境ECの返品・在庫を海外で再流通",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "グローバル展開（米国開始済）",
    "keywords": [
      "越境EC",
      "返品",
      "再流通",
      "サーキュラーエコノミー",
      "国際物流"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://thephage.life/recruit",
    "founded_year": "2021",
    "latest_round": "Pre-Series A",
    "latest_round_date": "2024"
  },
  {
    "id": "GV-054",
    "name": "スカイゲートテクノロジズ",
    "nameEn": "Skygate Technologies",
    "sector": "DeepTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "粟津 昂規",
    "summary": "防衛テクノロジーで国家安全保障に貢献",
    "hiringNeeds": "エンジニア",
    "growthChallenges": "製品開発・量産化",
    "keywords": [
      "防衛テック",
      "ドローン",
      "ロボティクス",
      "国防"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://ecrowd.co.jp/recruit",
    "founded_year": "2020",
    "latest_round": "",
    "latest_round_date": ""
  },
  {
    "id": "GV-055",
    "name": "MiRESSO",
    "nameEn": "MiRESSO",
    "sector": "DeepTech",
    "stage": "Seed",
    "teamSize": "1-10名",
    "ceo": "中道 勝",
    "summary": "核融合の社会実装を鉱物資源供給で支える",
    "hiringNeeds": "CxO, プラントエンジニア, 研究開発",
    "growthChallenges": "パイロットプラント建設（2027年目標）",
    "keywords": [
      "核融合",
      "ベリリウム",
      "低温精製",
      "エネルギー",
      "ディープテック"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2023",
    "latest_round": "Seed",
    "latest_round_date": "2024"
  },
  {
    "id": "GV-056",
    "name": "ジャパンキャリア",
    "nameEn": "JapanCareer",
    "sector": "HR Tech",
    "stage": "Pre-Seed",
    "teamSize": "1-10名",
    "ceo": "吉田 杏佑",
    "summary": "外国籍人材と国内企業のマッチング",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "外国籍人材基盤構築",
    "keywords": [
      "外国人採用",
      "人材マッチング",
      "共生社会",
      "人手不足"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.wantedly.com/companies/japancareer",
    "founded_year": "2024",
    "latest_round": "Pre-Seed",
    "latest_round_date": "2025"
  },
  {
    "id": "GV-057",
    "name": "ザ・ファージ",
    "nameEn": "THE PHAGE",
    "sector": "Health Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "德永 翔平",
    "summary": "血糖値の個別化コントロールで人類の健康課題に挑む",
    "hiringNeeds": "研究者, BizDev",
    "growthChallenges": "社会実装の加速",
    "keywords": [
      "血糖値",
      "腸内細菌",
      "ファージ",
      "個別化医療",
      "ヘルスケア"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://entaar.com/recruit",
    "founded_year": "2021",
    "latest_round": "Pre-Series A",
    "latest_round_date": "2025"
  },
  {
    "id": "GV-058",
    "name": "NOMU",
    "nameEn": "NOMU ENTERPRISE",
    "sector": "FoodTech",
    "stage": "Pre-Seed",
    "teamSize": "1-10名",
    "ceo": "森國 麦",
    "summary": "パーソナライズドリンクで新しい食体験を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "製品開発・市場拡大",
    "keywords": [
      "パーソナライズ",
      "ドリンク",
      "フードテック"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2022",
    "latest_round": "Seed",
    "latest_round_date": "2025"
  },
  {
    "id": "GV-059",
    "name": "Entaar",
    "nameEn": "Entaar",
    "sector": "Enterprise DX",
    "stage": "Pre-Series A",
    "teamSize": "1-10名",
    "ceo": "齋藤 大和",
    "summary": "大企業のIT投資をデータとAIで最適化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "プロダクト開発",
    "keywords": [
      "IT投資",
      "データベース",
      "AI共創",
      "エンタープライズ",
      "DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（要調査）",
    "founded_year": "2024",
    "latest_round": "Pre-Series A",
    "latest_round_date": "2025"
  },
  {
    "id": "GV-060",
    "name": "FormX",
    "nameEn": "FormX",
    "sector": "FinTech",
    "stage": "Seed",
    "teamSize": "1-10名",
    "ceo": "時田 知典",
    "summary": "上場企業の開示業務をDXで効率化",
    "hiringNeeds": "フロントエンドエンジニア",
    "growthChallenges": "プロダクト開発（2025年8月β版）",
    "keywords": [
      "ディスクロージャー",
      "開示",
      "XBRL",
      "上場企業",
      "IR"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）",
    "founded_year": "2023",
    "latest_round": "Seed",
    "latest_round_date": "2025"
  },
  {
    "id": "GV-064",
    "name": "匠技研工業",
    "nameEn": "Takumi Giken Kogyo",
    "sector": "Manufacturing Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "前田 将太",
    "summary": "町工場の経営DXを匠フォースで実現",
    "hiringNeeds": "エンジニア, セールス",
    "growthChallenges": "製造業市場拡大",
    "keywords": [
      "製造DX",
      "町工場",
      "見積",
      "工場経営",
      "匠フォース"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/takumigiken",
    "founded_year": "2020",
    "latest_round": "Series A",
    "latest_round_date": "2024-12"
  },
  {
    "id": "GV-065",
    "name": "カイタク",
    "nameEn": "Kaitak",
    "sector": "AI / ML",
    "stage": "Seed",
    "teamSize": "1-10名",
    "ceo": "松木 友範",
    "summary": "AI電話エージェントでコミュニケーションを革新",
    "hiringNeeds": "AIエンジニア",
    "growthChallenges": "プロダクトPMF",
    "keywords": [
      "AI電話",
      "コールセンター",
      "音声AI",
      "エージェント",
      "スパ電"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/kaitak",
    "founded_year": "2022",
    "latest_round": "Seed",
    "latest_round_date": "2025"
  },
  {
    "id": "GV-067",
    "name": "Tensor Energy",
    "nameEn": "Tensor Energy",
    "sector": "CleanTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "堀 菜々 & フィルター・ヴィンセント",
    "summary": "再エネ×蓄電池のオペレーティングシステムを構築",
    "hiringNeeds": "AIエンジニア, BizDev, エネルギー専門家",
    "growthChallenges": "顧客基盤拡大・蓄電池連携の本格化",
    "keywords": [
      "再エネ",
      "蓄電池",
      "FIP",
      "AI発電予測",
      "電力取引",
      "GX",
      "オーケストレーション",
      "Tensor Cloud"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/TensorEnergy",
    "founded_year": "2021",
    "latest_round": "Pre-Series A",
    "latest_round_date": "2024"
  },
  {
    "id": "GV-068",
    "name": "ケミカン",
    "nameEn": "Chemikan",
    "sector": "Chemical SaaS",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "清水俊博",
    "summary": "製品含有化学物質の調査・管理業務をデータ化するSaaSプラットフォーム",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "化学物質",
      "chemSHERPA",
      "SaaS",
      "製造業"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://chemikan.co.jp/recruit",
    "founded_year": "2014",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-069",
    "name": "Homedy",
    "nameEn": "Homedy",
    "sector": "Real Estate",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "Duc Nguyen Ba",
    "summary": "ベトナムにおける不動産売買・賃貸ポータルプラットフォーム",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "不動産",
      "ベトナム",
      "ポータル"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2015",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-070",
    "name": "NiCOLA",
    "nameEn": "NiCOLA",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "テクノロジーを活用して飲食店と顧客の関係を豊かにするサービスを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "飲食",
      "テック",
      "店舗"
    ],
    "target_market": "B2B2C",
    "target_segment": "SMB",
    "recruitUrl": "https://en-gage.net/nicola/",
    "founded_year": "2017",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-071",
    "name": "BizteX",
    "nameEn": "BizteX",
    "sector": "RPA/Automation",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "嶋田光敏",
    "summary": "クラウドRPA「BizteX cobit」やiPaaS「BizteX Connect」等の業務自動化ソリューションを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "RPA",
      "自動化",
      "iPaaS",
      "クラウド"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://herp.careers/v1/biztex",
    "founded_year": "2015",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-072",
    "name": "Non Brokers",
    "nameEn": "HOUSE REVO",
    "sector": "Real Estate Tech",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "不動産売買プラットフォーム「いえうり」「チョク買い」等を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "不動産",
      "売買",
      "マッチング"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://non-brokers.jbplt.jp/",
    "founded_year": "",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-073",
    "name": "Mosh",
    "nameEn": "MOSH",
    "sector": "Creator Economy",
    "stage": "Series C",
    "teamSize": "不明",
    "ceo": "籔和弥",
    "summary": "個人がネットでサービス販売できるプラットフォーム「MOSH」を運営、登録クリエイター8万人超",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "クリエイター",
      "サービス販売",
      "個人事業主"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://careers.mosh.jp/",
    "founded_year": "2017",
    "latest_round": "Series C",
    "latest_round_date": ""
  },
  {
    "id": "GV-074",
    "name": "Yourniture",
    "nameEn": "Yourniture",
    "sector": "D2C/Furniture",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "1cm単位でカスタマイズ可能なオンラインパーソナライズ家具D2Cブランド",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "家具",
      "カスタマイズ",
      "D2C"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2014",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-075",
    "name": "REGALI",
    "nameEn": "Brewtope",
    "sector": "FoodTech/D2C",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "金澤俊昌",
    "summary": "クラフトビールのサブスクリプションサービス「Otomoni」を運営、400以上の醸造所と提携",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "クラフトビール",
      "サブスク",
      "D2C"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://herp.careers/v1/regali",
    "founded_year": "2014",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-076",
    "name": "ロジクラ",
    "nameEn": "Logikura",
    "sector": "Logistics SaaS",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "入荷・在庫管理・出荷までの物流オペレーションを一元管理するクラウド在庫管理システム",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "在庫管理",
      "物流",
      "クラウド",
      "EC"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://corp.logikura.jp/recruit",
    "founded_year": "",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-077",
    "name": "Linc",
    "nameEn": "Linc",
    "sector": "HR Tech/EdTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "仲思遥",
    "summary": "外国人材向けオンライン学習・就職支援サービスを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "外国人材",
      "就職支援",
      "学習"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://linc-info.com/recruit-top/",
    "founded_year": "",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-078",
    "name": "バベル",
    "nameEn": "Babel",
    "sector": "Digital Agency/AdTech",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "日中の動画メディア・広告展開を行うデジタルエージェンシー",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "動画",
      "広告",
      "日中",
      "メディア"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://herp.careers/v1/babel",
    "founded_year": "",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-079",
    "name": "PSYGIG",
    "nameEn": "PSYGIG",
    "sector": "IoT/Robotics",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Gary Lo",
    "summary": "ドローン・自律走行車・ロボット向けモビリティIoTプラットフォームを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "IoT",
      "ドローン",
      "ロボット",
      "自律走行"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://en-jp.wantedly.com/companies/psygig/about",
    "founded_year": "2017",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-080",
    "name": "空き家活用",
    "nameEn": "Akikatsu",
    "sector": "Real Estate Tech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "和田貴充",
    "summary": "空き家の総合プロデュース企業、自治体向け空き家管理・利活用サービス「アキカツ」を展開",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "空き家",
      "不動産",
      "自治体",
      "地方創生"
    ],
    "target_market": "B2B2C",
    "target_segment": "SMB",
    "recruitUrl": "https://en-gage.net/aki-katsu_saiyo/",
    "founded_year": "2014",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-081",
    "name": "Mobilkamu",
    "nameEn": "Mobilkamu",
    "sector": "Automotive",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "Wilton Halim",
    "summary": "インドネシアにおけるオンライン新車購入プラットフォーム",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "自動車",
      "インドネシア",
      "EC"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.jobstreet.co.id/companies/mobilkamu-group-indonesia-168555790138578",
    "founded_year": "2015",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-082",
    "name": "amplified.ai",
    "nameEn": "amplified.ai",
    "sector": "AI/IP Tech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Sam Davis",
    "summary": "AI駆動の知的財産データ検索・分析プラットフォームを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "AI",
      "知財",
      "特許",
      "分析"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://wellfound.com/company/amplified-ai",
    "founded_year": "2017",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-083",
    "name": "ライフクエスト",
    "nameEn": "Life Quest",
    "sector": "HealthTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "MCI・ギャンブル依存症等を対象としたデジタル創薬・治療用アプリの研究開発",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "デジタル治療",
      "創薬",
      "アプリ"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "",
    "founded_year": "",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-084",
    "name": "CO-NECT",
    "nameEn": "CO-NECT",
    "sector": "SaaS/BtoB Commerce",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "田口雄介",
    "summary": "BtoB受発注システム「CO-NECT」を提供、39,000社が導入",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "受発注",
      "BtoB",
      "SaaS",
      "EC"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://herp.careers/v1/conect",
    "founded_year": "2015",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-085",
    "name": "アットハース",
    "nameEn": "AtHearth",
    "sector": "Real Estate Tech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "外国人向け多言語賃貸仲介プラットフォーム「AtHearth」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "外国人",
      "賃貸",
      "多言語"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://about.athearth.com/careers",
    "founded_year": "2015",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-086",
    "name": "Opsigo",
    "nameEn": "Opsigo",
    "sector": "Travel Tech/SaaS",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "Edward Nelson Jusuf",
    "summary": "インドネシアの企業向け出張管理・旅行予約プラットフォーム「Opsicorp」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "出張管理",
      "旅行",
      "インドネシア"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "",
    "founded_year": "2014",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-087",
    "name": "Sozi",
    "nameEn": "Sozi",
    "sector": "Creator Economy",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "宮村帝明",
    "summary": "クリエイター向けファンレターサービス「OFUSE」やイラストアプリ「pib」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "クリエイター",
      "ファンレター",
      "イラスト"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://herp.careers/v1/sozi",
    "founded_year": "2017",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-088",
    "name": "Aerial Partners",
    "nameEn": "Aerial Partners",
    "sector": "FinTech/Crypto",
    "stage": "Series B",
    "teamSize": "不明",
    "ceo": "沼澤健人",
    "summary": "暗号資産の損益計算ツール「Gtax」やWeb3事業者向け経理サポートツールを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "暗号資産",
      "税務",
      "Web3",
      "経理"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://herp.careers/v1/aerialp",
    "founded_year": "2017",
    "latest_round": "Series B",
    "latest_round_date": ""
  },
  {
    "id": "GV-089",
    "name": "ジャングルX",
    "nameEn": "Jungle X",
    "sector": "Sports/Betting",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "直江文忠",
    "summary": "英国賭博ライセンスを取得したスポーツベッティングプラットフォーム「JUNGLE Bet」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "スポーツ",
      "ベッティング",
      "エンタメ"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://jp.jungle.xyz/career",
    "founded_year": "2016",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-090",
    "name": "Airsalon",
    "nameEn": "Airsalon",
    "sector": "Beauty Tech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "阿部竜作",
    "summary": "フリーランス美容師と面貸し美容室のマッチングプラットフォームを運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "美容師",
      "フリーランス",
      "マッチング"
    ],
    "target_market": "B2B2C",
    "target_segment": "SMB",
    "recruitUrl": "",
    "founded_year": "2015",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-091",
    "name": "Crezit",
    "nameEn": "Crezit",
    "sector": "FinTech",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "矢部寿明",
    "summary": "与信プラットフォーム「Credit as a Service (ZEN)」を提供し、企業の金融サービス立ち上げを支援",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "与信",
      "金融",
      "CaaS"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://career.crezit-holdings.com/",
    "founded_year": "2019",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-092",
    "name": "Skillnote",
    "nameEn": "Skillnote",
    "sector": "Manufacturing SaaS",
    "stage": "Series C",
    "teamSize": "不明",
    "ceo": "山川隆史",
    "summary": "製造業特化のスキル管理・人材育成システム「SKILL NOTE」を提供、250社以上が導入",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "製造業",
      "スキル管理",
      "人材育成"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://career.skillnote.jp/",
    "founded_year": "2016",
    "latest_round": "Series C",
    "latest_round_date": ""
  },
  {
    "id": "GV-093",
    "name": "プランティオ",
    "nameEn": "Plantio",
    "sector": "AgriTech",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "芹澤孝悦",
    "summary": "IoTプランターやシェア型コミュニティ農園を通じた都市農プラットフォーム「grow」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "農業",
      "IoT",
      "都市農",
      "コミュニティ"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://sg.wantedly.com/companies/plantio2/projects",
    "founded_year": "2015",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-094",
    "name": "Logisly",
    "nameEn": "Logisly",
    "sector": "Logistics",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "Roolin Njotosetiadi",
    "summary": "インドネシア最大のB2Bデジタルトラッキングプラットフォーム、荷主と運送会社をつなぐ",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "物流",
      "インドネシア",
      "トラック",
      "マッチング"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://logisly.com/careers",
    "founded_year": "2019",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-095",
    "name": "Pergi Kuliner",
    "nameEn": "Pergi Kuliner",
    "sector": "FoodTech/Media",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Oswin Liandow",
    "summary": "インドネシアNo.1のレストランディレクトリ・レビューアプリ",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "レストラン",
      "レビュー",
      "インドネシア"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.karir.com/companies/40783",
    "founded_year": "2014",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-096",
    "name": "WISE EGG",
    "nameEn": "WISE EGG",
    "sector": "FinTech",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "松浦崇",
    "summary": "東南アジアで金融商品マッチングプラットフォーム「MoneyDuck」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "金融",
      "東南アジア",
      "保険",
      "マッチング"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://sg.wantedly.com/companies/hellowiseegg",
    "founded_year": "2019",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-097",
    "name": "リース",
    "nameEn": "Rease",
    "sector": "FinTech/PropTech",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "中道康徳",
    "summary": "フリーランス向け家賃保証付きお部屋探しアプリ「smeta」および家賃保証クラウドを運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "家賃保証",
      "フリーランス",
      "不動産"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.green-japan.com/company/8559",
    "founded_year": "2018",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-098",
    "name": "dreamstock",
    "nameEn": "dreamstock",
    "sector": "Sports Tech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "松永マルセロハルオ",
    "summary": "サッカー専用スカウティングアプリ「DSFootball」を運営、FIFAエージェントライセンス取得",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "サッカー",
      "スカウティング",
      "スポーツ"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://sg.wantedly.com/companies/dreamstock",
    "founded_year": "2016",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-099",
    "name": "eDoctor",
    "nameEn": "eDoctor",
    "sector": "HealthTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Vu Thanh Long",
    "summary": "ベトナムにおける遠隔医療相談モバイルアプリおよび健康スクリーニングサービスを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "遠隔医療",
      "ベトナム",
      "ヘルスケア"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://itviec.com/companies/edoctor",
    "founded_year": "2014",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-100",
    "name": "Napps Technologies",
    "nameEn": "Napps Technologies",
    "sector": "SaaS/NoCode",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "榎本友幸",
    "summary": "ノーコードでアプリ作成・配信ができるプラットフォーム「NappyTown」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ノーコード",
      "アプリ開発",
      "プラットフォーム"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.in-fra.jp/next/companies/4497",
    "founded_year": "2017",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-101",
    "name": "コノセル",
    "nameEn": "Conocer",
    "sector": "EdTech",
    "stage": "Series B",
    "teamSize": "不明",
    "ceo": "田辺理",
    "summary": "テクノロジー×リアルのハイブリッド学習塾「個別指導コノ塾」を全国111校展開",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "学習塾",
      "教育",
      "個別指導",
      "テック"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://herp.careers/v1/conocer",
    "founded_year": "2019",
    "latest_round": "Series B",
    "latest_round_date": ""
  },
  {
    "id": "GV-102",
    "name": "クラウドローン",
    "nameEn": "CrowdLoan",
    "sector": "FinTech",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "村田大輔",
    "summary": "個人向け融資マッチングプラットフォーム「クラウドローン」を運営、30行以上の金融機関と提携",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "融資",
      "ローン",
      "金融機関",
      "マッチング"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://careers.crowdloan.jp/",
    "founded_year": "2018",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-103",
    "name": "Connect Afya",
    "nameEn": "Connect Afya",
    "sector": "HealthTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "島田陽一",
    "summary": "ケニアで医療診断・ラボテストサービスを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "医療",
      "ケニア",
      "アフリカ",
      "診断"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2018",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-104",
    "name": "Activaid",
    "nameEn": "SmarTrial",
    "sector": "HealthTech/SaaS",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "長谷部靖明",
    "summary": "IBD患者向けソーシャルデータプラットフォームおよび臨床試験プロジェクト管理サービス「SmarTrial」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "臨床試験",
      "ヘルスケア",
      "SaaS"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "",
    "founded_year": "2018",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-105",
    "name": "FUNEE",
    "nameEn": "digdig",
    "sector": "Fashion/C2C",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "楊承峻",
    "summary": "ファッション特化型フリマプラットフォーム「digdig」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ファッション",
      "フリマ",
      "C2C"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://herp.careers/careers/companies/funee/jobs/dvIyYVNQVxtN",
    "founded_year": "2019",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-106",
    "name": "Vietcetera",
    "nameEn": "Vietcetera",
    "sector": "Media",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "Hao Tran",
    "summary": "ベトナムを代表するデジタルメディアプラットフォーム、ポッドキャストやビジネスメディアを展開",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "メディア",
      "ベトナム",
      "ポッドキャスト"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://vietcetera.com/careers",
    "founded_year": "2016",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-107",
    "name": "エナーバンク",
    "nameEn": "Enabank",
    "sector": "EnergyTech",
    "stage": "Series B",
    "teamSize": "不明",
    "ceo": "村中健一",
    "summary": "日本最大級の電力オークション「エネオク」および脱炭素支援サービスを運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "電力",
      "エネルギー",
      "オークション",
      "脱炭素"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://herp.careers/v1/enerbank",
    "founded_year": "2018",
    "latest_round": "Series B",
    "latest_round_date": ""
  },
  {
    "id": "GV-108",
    "name": "FOODCODE",
    "nameEn": "FOODCODE",
    "sector": "FoodTech",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "西海和久",
    "summary": "カスタマイズカレー「TOKYO MIX CURRY」をアプリ注文で展開、飲食×テクノロジーの一気通貫モデル",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "飲食",
      "カレー",
      "アプリ",
      "テック"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.wantedly.com/companies/company_foodcode/projects",
    "founded_year": "2018",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-109",
    "name": "Nectico",
    "nameEn": "Nectico",
    "sector": "SaaS",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Amry Fitra Amanah",
    "summary": "インドネシアの協同組合向けERP・B2Bマーケットプレイスを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ERP",
      "協同組合",
      "インドネシア"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.nectico.com/en/beranda/career/",
    "founded_year": "2019",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-110",
    "name": "miive",
    "nameEn": "miive",
    "sector": "HR Tech/FinTech",
    "stage": "Series B",
    "teamSize": "不明",
    "ceo": "栗田廉",
    "summary": "Visaプリペイドカード型の福利厚生プラットフォーム「miive」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "福利厚生",
      "プリペイドカード",
      "HR"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://herp.careers/careers/companies/miive",
    "founded_year": "2020",
    "latest_round": "Series B",
    "latest_round_date": ""
  },
  {
    "id": "GV-111",
    "name": "エムボックス",
    "nameEn": "mbox",
    "sector": "HealthTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "AGA（男性型脱毛症）セルフケアブランド「HIX」および便秘チェックサービス「Bebo」を展開",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "AGA",
      "ヘルスケア",
      "セルフケア"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2018",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-112",
    "name": "Vitalogue Health",
    "nameEn": "Vitalogue Health",
    "sector": "FemTech/HealthTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "長谷川彩子",
    "summary": "自宅で郵送ホルモン検査ができる「canvas」および漢方相談サービスを運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ホルモン検査",
      "漢方",
      "フェムテック"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://herp.careers/v1/vitalogue",
    "founded_year": "2020",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-113",
    "name": "Finantier",
    "nameEn": "Finantier",
    "sector": "FinTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Diego Rojas",
    "summary": "東南アジアのオープンファイナンスAPIプラットフォーム、Y Combinator卒",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "オープンファイナンス",
      "API",
      "東南アジア"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://finantier.co/careers/",
    "founded_year": "2020",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-114",
    "name": "AmoebaX",
    "nameEn": "AmoebaX",
    "sector": "AgriTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "河野邦彦",
    "summary": "ケニア・ナイロビで野菜卸売プラットフォーム「YasaFi」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "農業",
      "ケニア",
      "アフリカ",
      "野菜"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "",
    "founded_year": "2018",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-115",
    "name": "ナッジ",
    "nameEn": "Nudge",
    "sector": "FinTech",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "沖田貴史",
    "summary": "次世代型スマホ連動Visaクレジットカード「Nudge」を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "クレジットカード",
      "フィンテック",
      "Z世代"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://nudge.works/talents",
    "founded_year": "2020",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-116",
    "name": "エイトス",
    "nameEn": "Eitoss",
    "sector": "SaaS/EHS",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "嶋田亘",
    "summary": "デスクレスワーカー向け改善提案クラウド「Cayzen」を運営、EHS×現場DX",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "現場DX",
      "改善提案",
      "EHS",
      "製造業"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://herp.careers/v1/eitoss",
    "founded_year": "2019",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-117",
    "name": "メンテモ",
    "nameEn": "Mentemo",
    "sector": "Mobility",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "若月佑樹",
    "summary": "自動車整備・鈑金工場をネット検索・予約できるマーケットプレイス「メンテモ」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "自動車",
      "整備",
      "マーケットプレイス"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://open.talentio.com/r/1/c/mentemo/homes/2639",
    "founded_year": "2017",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-118",
    "name": "PRES",
    "nameEn": "PRES",
    "sector": "SaaS/Academia",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "大滝翔士",
    "summary": "研究活動DXプラットフォーム「Wizdom」と産学連携マッチング「Radstar」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "研究",
      "産学連携",
      "大学",
      "DX"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "",
    "founded_year": "2018",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-119",
    "name": "amptalk",
    "nameEn": "amptalk",
    "sector": "SaaS/SalesTech",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "猪瀬竜馬",
    "summary": "商談の自動書き起こし・解析ツール「amptalk」およびAIロープレ「amptalk coach」を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "商談",
      "書き起こし",
      "AI",
      "セールス"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://amptalk.co.jp/recruit/top",
    "founded_year": "2020",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-120",
    "name": "Fundiin",
    "nameEn": "Fundiin",
    "sector": "FinTech/BNPL",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "Nguyen Anh Cuong",
    "summary": "ベトナム最大級のBNPL（後払い決済）プラットフォーム、2,000以上の加盟店と提携",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "BNPL",
      "後払い",
      "ベトナム",
      "決済"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://itviec.com/companies/fundiin",
    "founded_year": "2019",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-121",
    "name": "Teatis",
    "nameEn": "Teatis",
    "sector": "FoodTech/HealthTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "高頭博志",
    "summary": "米国で糖尿病患者向け代替食・スーパーフード粉末飲料「Teatis」を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "糖尿病",
      "食品",
      "ヘルスケア",
      "米国"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2021",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-122",
    "name": "イークラウド",
    "nameEn": "eCrowd",
    "sector": "FinTech",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "波多江直彦",
    "summary": "株式投資型クラウドファンディングプラットフォームを運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "クラウドファンディング",
      "投資",
      "株式"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://en-gage.net/ecrowd_career/",
    "founded_year": "2018",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-123",
    "name": "Airboxr",
    "nameEn": "Airboxr",
    "sector": "SaaS/E-commerce",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Saptarshi Nath",
    "summary": "ECブランド向けデータ自動化プラットフォーム、Shopify等と連携",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "EC",
      "データ分析",
      "Shopify"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://jobs.airboxr.com/",
    "founded_year": "2020",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-124",
    "name": "TiERRAS",
    "nameEn": "TiERRAS",
    "sector": "D2C/Beauty",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "吉田",
    "summary": "ヘルスケア発想のD2Cエイジングケアブランド「SKINFONIA」を日本と中国で展開",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "スキンケア",
      "D2C",
      "エイジングケア"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://en-jp.wantedly.com/companies/company_2454760/projects",
    "founded_year": "2020",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-125",
    "name": "DXER",
    "nameEn": "DXER",
    "sector": "SaaS/IT",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "向井拓真",
    "summary": "企業の情報システム部向けAI×BPOサービス「シスクル」を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "情シス",
      "IT",
      "BPO",
      "AI"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://herp.careers/v1/dxer",
    "founded_year": "2020",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-126",
    "name": "Selly",
    "nameEn": "Selly",
    "sector": "E-commerce",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "Tuan Thong",
    "summary": "ベトナムのソーシャルコマースプラットフォーム「Selly」およびキャッシュバックアプリ「Cashbag」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ソーシャルコマース",
      "ベトナム",
      "EC"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://itviec.com/companies/selly",
    "founded_year": "2021",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-127",
    "name": "BeepBeep",
    "nameEn": "BeepBeep",
    "sector": "QuickCommerce",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Gaetano Seminario",
    "summary": "東南アジアで15分即配グロサリーサービスを展開",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "即配",
      "グロサリー",
      "東南アジア"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2021",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-128",
    "name": "シャトル",
    "nameEn": "Shuttle",
    "sector": "FinTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "建原史朗",
    "summary": "親がアプリから送金し子供がプリペイドカードで利用できる子供向けプリペイドカードサービス「ShuttlePay」を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "子供",
      "プリペイドカード",
      "送金",
      "フィンテック"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://herp.careers/v1/shuttle",
    "founded_year": "2019",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-129",
    "name": "Rey Assurance",
    "nameEn": "Rey Assurance",
    "sector": "InsurTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Evan Tanotogono",
    "summary": "インドネシアで健康・生命保険をサブスクリプション型で提供するデジタル保険プラットフォーム",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "保険",
      "インドネシア",
      "サブスク"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2021",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-130",
    "name": "ElevationSpace",
    "nameEn": "ElevationSpace",
    "sector": "SpaceTech",
    "stage": "Pre-Series B",
    "teamSize": "不明",
    "ceo": "小林稜平",
    "summary": "東北大学発の宇宙スタートアップ、再突入衛星や宇宙環境利用・回収プラットフォームを開発",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "宇宙",
      "衛星",
      "ディープテック"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://herp.careers/v1/elspace",
    "founded_year": "2021",
    "latest_round": "Pre-Series B",
    "latest_round_date": ""
  },
  {
    "id": "GV-131",
    "name": "Payn",
    "nameEn": "Payn",
    "sector": "SaaS/Hospitality",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "山下恭平",
    "summary": "キャンセル料の請求・回収業務を自動化するツール「Payn」を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "キャンセル料",
      "自動化",
      "ホテル"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://herp.careers/v1/payn",
    "founded_year": "2022",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-132",
    "name": "MVillage",
    "nameEn": "MVillage",
    "sector": "Hospitality",
    "stage": "Series B",
    "teamSize": "不明",
    "ceo": "Nguyen Hai Ninh",
    "summary": "ベトナムで若者向けのコリビング・コワーキングスペースを展開",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "コリビング",
      "コワーキング",
      "ベトナム"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2020",
    "latest_round": "Series B",
    "latest_round_date": ""
  },
  {
    "id": "GV-133",
    "name": "movus technologies",
    "nameEn": "movus technologies",
    "sector": "Mobility/FinTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "酒井丈虎",
    "summary": "インドネシアでモビリティ×金融インフラを構築し、IoT活用のカーサブスクリプションサービスを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "モビリティ",
      "カーサブスク",
      "インドネシア",
      "IoT"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.wantedly.com/companies/company_269709/projects",
    "founded_year": "2021",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-134",
    "name": "Progummy",
    "nameEn": "Progummy",
    "sector": "EdTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "石橋康大",
    "summary": "世界初のリアルタイム共同編集機能を備えたビジュアルプログラミングアプリを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "プログラミング教育",
      "子供",
      "アプリ"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2020",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-135",
    "name": "InsightX",
    "nameEn": "InsightX",
    "sector": "SaaS/AI",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "中澤弘樹",
    "summary": "BtoC企業向けのCX変革AIプラットフォーム「InsightX」を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "CX",
      "AI",
      "パーソナライズ"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://careers.insightx.tech/",
    "founded_year": "2021",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-136",
    "name": "AC Biode",
    "nameEn": "AC Biode",
    "sector": "CleanTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Naoji Kubo",
    "summary": "交流電池、廃プラスチック解重合触媒等を開発する化学テックスタートアップ",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "電池",
      "クリーンテック",
      "化学",
      "環境"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://acbiode.com/careers/",
    "founded_year": "2019",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-137",
    "name": "Mined",
    "nameEn": "Mined",
    "sector": "EdTech",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "前田智大",
    "summary": "子供がロールモデルから直接学べるプラットフォーム「スコラボ」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "教育",
      "ロールモデル",
      "子供"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.wantedly.com/companies/company_6382744",
    "founded_year": "2020",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-138",
    "name": "TAIAN",
    "nameEn": "TAIAN",
    "sector": "SaaS/Bridal",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "村田真理子",
    "summary": "ブライダル・バンケット業界に特化したクラウドSaaS「Oiwaii」等を提供、全国400以上の事業者が利用",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ブライダル",
      "SaaS",
      "ウェディング"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/taian/projects",
    "founded_year": "2020",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-139",
    "name": "Flucle",
    "nameEn": "HRbase",
    "sector": "SaaS/HR",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "三田弘道",
    "summary": "社労士・企業向け労務相談プラットフォーム「HRbase PRO」を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "労務",
      "社労士",
      "HR",
      "SaaS"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://hrbase.recruitment.jp/",
    "founded_year": "2015",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-140",
    "name": "Conoris",
    "nameEn": "Conoris",
    "sector": "SaaS/Security",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "クラウドサービスのセキュリティチェック・委託先リスク管理を効率化するSaaSプロダクト群を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "セキュリティ",
      "リスク管理",
      "SaaS"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://herp.careers/v1/mitsucaru",
    "founded_year": "2020",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-141",
    "name": "アルバトロス・テクノロジー",
    "nameEn": "Albatross Technology",
    "sector": "CleanTech/Wind",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "秋元博路",
    "summary": "浮体式洋上風車「浮遊軸型風車(FAWT)」を開発",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "洋上風力",
      "再エネ",
      "クリーンテック"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://www.albatross-technology.com/careers",
    "founded_year": "2022",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-142",
    "name": "Runchise",
    "nameEn": "Runchise",
    "sector": "SaaS/F&B",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Daniel Witono",
    "summary": "インドネシアの飲食業界向けPOS・アウトレット管理プラットフォームをE2Eで提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "POS",
      "飲食",
      "インドネシア",
      "SaaS"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://apply.workable.com/runchise/",
    "founded_year": "2022",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-143",
    "name": "Rootopia",
    "nameEn": "Rootopia",
    "sector": "FinTech/EdTech",
    "stage": "Pre-Seed",
    "teamSize": "不明",
    "ceo": "Nguyen Xuan Truong",
    "summary": "ベトナムで教育向けP2Pレンディングプラットフォームを運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "教育ローン",
      "P2P",
      "ベトナム"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2021",
    "latest_round": "Pre-Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-144",
    "name": "Mierba",
    "nameEn": "Mierba",
    "sector": "SaaS/HR",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "丸山樹",
    "summary": "中途採用向け職種別スキルチェックテストを提供するタレントアセスメントSaaS",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "採用",
      "スキルテスト",
      "アセスメント"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/company_9302277",
    "founded_year": "",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-145",
    "name": "Wareflex",
    "nameEn": "Wareflex",
    "sector": "Logistics",
    "stage": "Pre-Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "ベトナム初のオンデマンド倉庫プラットフォーム、100以上の倉庫ネットワークを展開",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "倉庫",
      "物流",
      "ベトナム",
      "オンデマンド"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "",
    "founded_year": "2022",
    "latest_round": "Pre-Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-146",
    "name": "コングラント",
    "nameEn": "Congrant",
    "sector": "SaaS/Social",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "佐藤正隆",
    "summary": "NPO・企業向けの寄付DXシステム「congrant」を提供、2,800以上の団体が利用",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "寄付",
      "NPO",
      "ソーシャル",
      "DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/company_congrant/projects",
    "founded_year": "2020",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-147",
    "name": "Khariis",
    "nameEn": "Khariis",
    "sector": "Food/Sake",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "秋月杏奈",
    "summary": "世界中の消費者・ソムリエ・酒蔵をつなぐ日本酒プラットフォーム「Sakeist」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "日本酒",
      "プラットフォーム",
      "グローバル"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2019",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-148",
    "name": "Sales Navi",
    "nameEn": "Sales Navi",
    "sector": "SaaS/SalesTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "田中大貴",
    "summary": "AIコーチが営業活動を指導・標準化する営業標準化システム「Sales Navi」を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "営業",
      "AI",
      "コーチング",
      "標準化"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/company_salesnavi/projects",
    "founded_year": "2021",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-149",
    "name": "Logpose Technologies",
    "nameEn": "Logpose Technologies",
    "sector": "SaaS/Logistics",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "羽室行光",
    "summary": "AI・データサイエンス技術で配車管理・配送計画を自動化する「AI配車アシスタント LOG」を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "配車",
      "物流",
      "AI",
      "自動化"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://careers.logpose.co.jp/",
    "founded_year": "2018",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-150",
    "name": "トドケール",
    "nameEn": "Todoker",
    "sector": "SaaS/Office",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "野島剛",
    "summary": "オフィス向け郵便物・配達物のクラウド管理ツール及びミニBPOサービス「クラウドメール室」を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "郵便物",
      "オフィス管理",
      "SaaS"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.todoker.com/recruit",
    "founded_year": "2018",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-151",
    "name": "CARESPACE",
    "nameEn": "CARESPACE",
    "sector": "HealthTech/Care",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "三浦亮",
    "summary": "ケアマネジャーと介護事業所をICTでつなぐプラットフォーム「CareSpace」を運営",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "介護",
      "ケアマネ",
      "ICT",
      "DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/company_3357489",
    "founded_year": "2020",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-152",
    "name": "Artefact Collective",
    "nameEn": "Kasagi Labo",
    "sector": "Entertainment/Anime",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "シンガポール拠点のアニメベンチャースタジオ、日本の正統派アニメをグローバルに展開",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "アニメ",
      "エンタメ",
      "グローバル"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.kasagilabo.com/careers",
    "founded_year": "2023",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-153",
    "name": "M&A Lead",
    "nameEn": "M&A Lead",
    "sector": "SaaS/M&A",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "坂本",
    "summary": "売り手ファーストのM&A仲介事業、M&Aアドバイザーマッチングサイト等を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "M&A",
      "仲介",
      "マッチング"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/company_9590660",
    "founded_year": "2022",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-154",
    "name": "StepChange",
    "nameEn": "StepChange",
    "sector": "SaaS/ESG",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Ankit Jain",
    "summary": "企業のESG指標管理・気候リスク対応・排出量削減を支援するサステナビリティSaaS",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ESG",
      "サステナビリティ",
      "気候変動"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://www.wantedly.com/companies/stepchange/projects",
    "founded_year": "2022",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-155",
    "name": "フレンドマイクローブ",
    "nameEn": "Friend Microbe",
    "sector": "BioTech/Environment",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "蟹江純一",
    "summary": "名古屋大学発、微生物を活用した排水処理・油脂分解・環境衛生技術を開発・提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "微生物",
      "排水処理",
      "環境",
      "バイオ"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://friendmicrobe.co.jp/recruit/entry-143.html",
    "founded_year": "2017",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-156",
    "name": "Haul",
    "nameEn": "Haul",
    "sector": "SaaS/HR",
    "stage": "Pre-Series A",
    "teamSize": "不明",
    "ceo": "平田拓嗣",
    "summary": "採用イネーブルメントSaaS「RekMA」を提供し、AIを活用した次世代型の採用支援を行う",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "採用",
      "AI",
      "SaaS",
      "HR"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://haulinc.jp/career/",
    "founded_year": "2018",
    "latest_round": "Pre-Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-157",
    "name": "24hMoney",
    "nameEn": "24hMoney",
    "sector": "FinTech/Media",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Phan Minh Tam",
    "summary": "ベトナムの金融・株式・不動産情報ソーシャルプラットフォーム",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "金融",
      "株式",
      "ベトナム",
      "メディア"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2019",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-158",
    "name": "OIKOS MUSIC",
    "nameEn": "OIKOS MUSIC",
    "sector": "Entertainment/Music",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "市村昭宏",
    "summary": "音楽の原盤権マーケットプレイス「ORF」を運営、アーティストとファンが権利を共同保有",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "音楽",
      "原盤権",
      "マーケットプレイス"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "",
    "founded_year": "2022",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-159",
    "name": "VCA COFFEE",
    "nameEn": "VCA COFFEE",
    "sector": "Agriculture/F&B",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "ベトナムのコーヒー豆サプライチェーンプラットフォーム",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "コーヒー",
      "ベトナム",
      "農業",
      "サプライチェーン"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "",
    "founded_year": "",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-160",
    "name": "メタセンシング",
    "nameEn": "Meta Sensing",
    "sector": "DeepTech",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "スマホに取り付け可能な超小型ラマン分光器「Raman EYE」とAI解析エージェントを開発",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "分光器",
      "計測",
      "AI",
      "ディープテック"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "",
    "founded_year": "",
    "latest_round": "Series A",
    "latest_round_date": ""
  },
  {
    "id": "GV-161",
    "name": "SaaSPay",
    "nameEn": "SaaSPay",
    "sector": "FinTech/BNPL",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "Prabhat Sahu",
    "summary": "SaaS・クラウドサブスクリプション向けBNPL(後払い)ソリューションを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "BNPL",
      "SaaS",
      "インド"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "",
    "founded_year": "2022",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-162",
    "name": "リチェルカ",
    "nameEn": "Recerqa",
    "sector": "SaaS/SCM",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "仕入・在庫・販売管理のSCM SaaS「RECERQA SCM」とAI-OCRサービスを提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "SCM",
      "在庫管理",
      "AI-OCR"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://herp.careers/v1/recerqa",
    "founded_year": "",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-163",
    "name": "楽々",
    "nameEn": "LaLa Corporation",
    "sector": "BioTech/Agriculture",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "駒場裕美",
    "summary": "脱炭素型・有機きのこ菌床製造装置を開発し、IoT技術で循環型きのこ農業を実現",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "きのこ",
      "農業",
      "バイオ",
      "循環型"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "",
    "founded_year": "2019",
    "latest_round": "Seed",
    "latest_round_date": ""
  },
  {
    "id": "GV-164",
    "name": "ミーバイオ",
    "nameEn": "miibio",
    "sector": "BioTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "早水建祥",
    "summary": "東京大学発、光スイッチタンパク質技術でバイオものづくりの物質生産スケールアップを支援",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "バイオ",
      "タンパク質",
      "東大発"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "",
    "founded_year": "2019",
    "latest_round": "Seed",
    "latest_round_date": ""
  }
];
module.exports = { PORTFOLIO };
