const PORTFOLIO = [
  {
    "id": "GV-002",
    "name": "タイミー",
    "nameEn": "Timee",
    "sector": "HR Tech",
    "stage": "Seed",
    "teamSize": "500名+",
    "ceo": "小川 嶺",
    "summary": "スキマバイトマッチングで人手不足を解決",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "スキマバイト",
      "ギグワーク",
      "人材マッチング",
      "短期雇用"
    ],
    "target_market": "B2B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://corp.timee.co.jp/recruit/"
  },
  {
    "id": "GV-003",
    "name": "助太刀",
    "nameEn": "Sukedachi",
    "sector": "Construction Tech",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "我妻 陽一",
    "summary": "建設現場の人材課題をテクノロジーで解決",
    "hiringNeeds": "BizDev, エンジニア",
    "growthChallenges": "建設業界の深耕",
    "keywords": [
      "建設",
      "人材",
      "マッチング",
      "給与",
      "現場DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://corp.suke-dachi.jp/recruit"
  },
  {
    "id": "GV-004",
    "name": "フォトラクション",
    "nameEn": "Photoruction",
    "sector": "Construction Tech",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "中島 貴春",
    "summary": "建設現場のDXを写真・図面管理で推進",
    "hiringNeeds": "セールス",
    "growthChallenges": "エンタープライズ展開",
    "keywords": [
      "建設DX",
      "写真管理",
      "工程管理",
      "BIM"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.photoruction.com/recruit"
  },
  {
    "id": "GV-005",
    "name": "Baseconnect",
    "nameEn": "Baseconnect",
    "sector": "Sales Tech",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "國重 侑輝",
    "summary": "企業DBで営業活動を効率化",
    "hiringNeeds": "データエンジニア",
    "growthChallenges": "データ品質向上",
    "keywords": [
      "企業データベース",
      "営業リスト",
      "B2Bデータ",
      "リード生成"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://baseconnect.in/about/recruit"
  },
  {
    "id": "GV-006",
    "name": "Autify",
    "nameEn": "Autify",
    "sector": "Dev Tools",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "近澤 良",
    "summary": "AIでソフトウェアテストを自動化",
    "hiringNeeds": "グローバルセールス",
    "growthChallenges": "グローバル展開",
    "keywords": [
      "テスト自動化",
      "QA",
      "ノーコード",
      "AI",
      "ソフトウェア品質"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://autify.com/ja/careers"
  },
  {
    "id": "GV-007",
    "name": "Zenport",
    "nameEn": "Zenport",
    "sector": "Logistics Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "国際物流のクラウド最適化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "グローバル展開",
    "keywords": [
      "国際物流",
      "サプライチェーン",
      "貿易DX",
      "クラウド"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/zenport"
  },
  {
    "id": "GV-008",
    "name": "シェルフィー",
    "nameEn": "Shelfy",
    "sector": "Construction Tech",
    "stage": "Seed",
    "teamSize": "11-50名",
    "ceo": "呂 俊輝（ロイ シュンキ）",
    "summary": "建設業界のITインフラを整える総合プラットフォーム",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "内装",
      "マッチング",
      "安全書類",
      "建設DX",
      "Greenfile.work"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.shelfy.co.jp/recruit"
  },
  {
    "id": "GV-009",
    "name": "Good Moneyger (VESTA)",
    "nameEn": "Good Moneyger",
    "sector": "FinTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "清水 俊博",
    "summary": "運用しないロボアドバイザーで無料の投資アドバイス",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ロボアドバイザー",
      "投資信託",
      "AI",
      "資産運用",
      "楽天証券"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-010",
    "name": "JobRainbow",
    "nameEn": "JobRainbow",
    "sector": "HR Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "星 賢人",
    "summary": "ダイバーシティ採用を推進するプラットフォーム",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "D&I市場拡大",
    "keywords": [
      "LGBT",
      "ダイバーシティ",
      "採用",
      "インクルージョン"
    ],
    "target_market": "B2B2C",
    "target_segment": "SMB",
    "recruitUrl": "https://jobrainbow.jp/recruit"
  },
  {
    "id": "GV-011",
    "name": "Docquity",
    "nameEn": "Docquity",
    "sector": "Health Tech",
    "stage": "Seed",
    "teamSize": "100-300名",
    "ceo": "Indranil Roychowdhury",
    "summary": "医師同士の知識共有で医療水準を向上",
    "hiringNeeds": "日本市場展開",
    "growthChallenges": "新市場参入",
    "keywords": [
      "医師",
      "SNS",
      "医療",
      "東南アジア",
      "CME"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://docquity.com/careers"
  },
  {
    "id": "GV-012",
    "name": "Qoala",
    "nameEn": "Qoala",
    "sector": "InsurTech",
    "stage": "Seed",
    "teamSize": "100-300名",
    "ceo": "Harshet Lunani",
    "summary": "デジタル保険で東南アジアの保険普及を推進",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "東南アジア展開",
    "keywords": [
      "保険",
      "インシュアテック",
      "東南アジア",
      "デジタル"
    ],
    "target_market": "B2C",
    "target_segment": "SMB",
    "recruitUrl": "https://www.qoala.id/en/career"
  },
  {
    "id": "GV-013",
    "name": "bobobox",
    "nameEn": "Bobobox",
    "sector": "Travel Tech",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "Indrayana Rustandi",
    "summary": "テクノロジーで宿泊体験を再定義",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "東南アジア展開",
    "keywords": [
      "カプセルホテル",
      "スマート宿泊",
      "インドネシア"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.linkedin.com/company/bfrfrrrobobox/jobs/"
  },
  {
    "id": "GV-014",
    "name": "Scheeme",
    "nameEn": "Scheeme",
    "sector": "GovTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "補助金申請をDXで簡単に",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "SME市場拡大",
    "keywords": [
      "補助金",
      "助成金",
      "中小企業",
      "行政DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/scheeme"
  },
  {
    "id": "GV-015",
    "name": "テックドクター",
    "nameEn": "TechDoctor",
    "sector": "Health Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "湊 和修",
    "summary": "ウェアラブルデータで健康管理を革新",
    "hiringNeeds": "データサイエンティスト",
    "growthChallenges": "エビデンス構築",
    "keywords": [
      "デジタルヘルス",
      "ウェアラブル",
      "健康管理",
      "予防医療"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://www.technology-doctor.com/recruit"
  },
  {
    "id": "GV-016",
    "name": "FastLabel",
    "nameEn": "FastLabel",
    "sector": "AI / ML",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "上田 英介",
    "summary": "AI開発を10倍速くするデータプラットフォーム",
    "hiringNeeds": "エンタープライズセールス",
    "growthChallenges": "大企業AI導入支援",
    "keywords": [
      "AI",
      "アノテーション",
      "教師データ",
      "MLOps",
      "データプラットフォーム"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://fastlabel.ai/careers"
  },
  {
    "id": "GV-017",
    "name": "HOKUTO",
    "nameEn": "HOKUTO",
    "sector": "Health Tech",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "五十嵐 健祐",
    "summary": "エビデンスベースの臨床支援で医療を変革",
    "hiringNeeds": "コンテンツ, エンジニア",
    "growthChallenges": "コンテンツ拡充とマネタイズ",
    "keywords": [
      "臨床支援",
      "医師向けアプリ",
      "エビデンス",
      "医療情報"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.wantedly.com/companies/company_2277005"
  },
  {
    "id": "GV-018",
    "name": "ROUTE06",
    "nameEn": "ROUTE06",
    "sector": "Enterprise DX",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "遠藤 崇史",
    "summary": "大企業のDXプラットフォーム構築を支援",
    "hiringNeeds": "エンジニア, PM",
    "growthChallenges": "エンタープライズ展開",
    "keywords": [
      "エンタープライズDX",
      "プラットフォーム構築",
      "デジタル変革"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://route06.co.jp/careers"
  },
  {
    "id": "GV-019",
    "name": "Acall",
    "nameEn": "Acall",
    "sector": "PropTech",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "長沼 斉寿",
    "summary": "ハイブリッドワーク時代のオフィス管理を一元化",
    "hiringNeeds": "グローバルセールス",
    "growthChallenges": "グローバル展開（シンガポール）",
    "keywords": [
      "スマートオフィス",
      "受付",
      "会議室管理",
      "ハイブリッドワーク"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.acall.inc/recruit"
  },
  {
    "id": "GV-021",
    "name": "Kamereo",
    "nameEn": "Kamereo",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "田中 卓",
    "summary": "飲食店の食材調達をデジタル化",
    "hiringNeeds": "オペレーション",
    "growthChallenges": "ベトナム全国展開",
    "keywords": [
      "食材調達",
      "B2B",
      "ベトナム",
      "飲食DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://kamereo.vn/tuyen-dung"
  },
  {
    "id": "GV-022",
    "name": "BUYMED",
    "nameEn": "BUYMED",
    "sector": "Health Tech",
    "stage": "Seed",
    "teamSize": "100-300名",
    "ceo": "Peter Nguyen",
    "summary": "医薬品流通をデジタルで効率化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "ベトナム全国拡大",
    "keywords": [
      "医薬品",
      "B2B",
      "ベトナム",
      "流通DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://career.buymed.com/"
  },
  {
    "id": "GV-023",
    "name": "Manabie",
    "nameEn": "Manabie",
    "sector": "EdTech",
    "stage": "Seed",
    "teamSize": "100-300名",
    "ceo": "本間 拓也",
    "summary": "東南アジアの教育格差をテクノロジーで解消",
    "hiringNeeds": "コンテンツ, エンジニア",
    "growthChallenges": "東南アジア拡大",
    "keywords": [
      "教育",
      "EdTech",
      "東南アジア",
      "ブレンデッドラーニング"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://manabie.com/careers"
  },
  {
    "id": "GV-024",
    "name": "Sinbad",
    "nameEn": "Sinbad",
    "sector": "Retail Tech",
    "stage": "Seed",
    "teamSize": "50-100名",
    "ceo": "不明",
    "summary": "インドネシアの小売流通をDXで効率化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "インドネシア拡大",
    "keywords": [
      "B2B EC",
      "小売",
      "FMCG",
      "インドネシア"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-025",
    "name": "Microverse",
    "nameEn": "Microverse",
    "sector": "Entertainment Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "IP×Web3で新しいコンテンツ経済圏を創出",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "Web3市場開拓",
    "keywords": [
      "NFT",
      "Web3",
      "IP",
      "コンテンツ",
      "マネタイズ"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-026",
    "name": "Oyraa",
    "nameEn": "Oyraa",
    "sector": "HR Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "必要な時にすぐ通訳を手配",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "グローバル展開",
    "keywords": [
      "通訳",
      "マッチング",
      "多言語",
      "リアルタイム"
    ],
    "target_market": "B2C",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-027",
    "name": "Petokoto",
    "nameEn": "PETOKOTO",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "大久保 泰介",
    "summary": "ペットの健康をフレッシュフードで支える",
    "hiringNeeds": "マーケティング",
    "growthChallenges": "ブランド拡大",
    "keywords": [
      "ペットフード",
      "フレッシュフード",
      "D2C",
      "ペットメディア"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.wantedly.com/companies/petokoto"
  },
  {
    "id": "GV-028",
    "name": "funfo",
    "nameEn": "funfo",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "飲食店のDXをモバイルオーダーで推進",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "飲食チェーン展開",
    "keywords": [
      "モバイルオーダー",
      "飲食DX",
      "店舗DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://funfo.co.jp/recruit"
  },
  {
    "id": "GV-029",
    "name": "GAXI",
    "nameEn": "GAXI",
    "sector": "EdTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "松原 良輔",
    "summary": "奨学金を変え、運命を変え、社会を変える",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "学生基盤拡大",
    "keywords": [
      "奨学金",
      "教育",
      "マッチング",
      "給付型"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://gaxi.co.jp/recruit"
  },
  {
    "id": "GV-030",
    "name": "Malme",
    "nameEn": "Malme",
    "sector": "Construction Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "土木設計をAIで革新",
    "hiringNeeds": "AIエンジニア",
    "growthChallenges": "プロダクト開発",
    "keywords": [
      "土木DX",
      "AI設計",
      "インフラ",
      "Structural Engine"
    ],
    "target_market": "B2C",
    "target_segment": "SMB",
    "recruitUrl": "https://www.malme.net/recruit"
  },
  {
    "id": "GV-031",
    "name": "UMAMI UNITED",
    "nameEn": "UMAMI UNITED",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "日本発の植物性代替卵で食の未来を創る",
    "hiringNeeds": "R&D, 海外営業",
    "growthChallenges": "海外展開（米国・欧州）",
    "keywords": [
      "代替卵",
      "植物性",
      "フードテック",
      "サステナブル"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-032",
    "name": "RePlayce",
    "nameEn": "RePlayce",
    "sector": "EdTech",
    "stage": "Series A",
    "teamSize": "10-30名",
    "ceo": "山本 将裕",
    "summary": "中高生と社会をつなぐ探究型キャリア教育",
    "hiringNeeds": "キャリアコーチ, エンジニア, 教育プログラム開発",
    "growthChallenges": "教育機関ネットワーク拡大",
    "keywords": [
      "キャリア教育",
      "探究学習",
      "中高生",
      "通信制高校",
      "はたらく部"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://replayce.co.jp/recruit"
  },
  {
    "id": "GV-033",
    "name": "モカブル",
    "nameEn": "Mokable",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "1-10名",
    "ceo": "糸山 彰徳",
    "summary": "コーヒーを「飲む」から「食べる」へ革新",
    "hiringNeeds": "R&D, 海外営業, マーケティング",
    "growthChallenges": "北米展開・ブランド構築",
    "keywords": [
      "食べるコーヒー",
      "フードテック",
      "サステナブル",
      "カーブアウト",
      "サントリー"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://mokable.jp/careers"
  },
  {
    "id": "GV-034",
    "name": "Al Travel",
    "nameEn": "Al Travel",
    "sector": "Travel Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "出張手配をクラウドで効率化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "エンタープライズ展開",
    "keywords": [
      "出張管理",
      "クラウド",
      "BTM",
      "旅行DX"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-035",
    "name": "Liberont",
    "nameEn": "Liberont",
    "sector": "Retail Tech",
    "stage": "Seed",
    "teamSize": "1-10名",
    "ceo": "大河 淳司, 小島 剛",
    "summary": "バイバック保証で新しい購買体験を創出",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "バイバック保証",
      "Buy Now Sell Later",
      "EC",
      "サーキュラー"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://liberont.com/career"
  },
  {
    "id": "GV-036",
    "name": "nonat",
    "nameEn": "nonat",
    "sector": "Health Tech",
    "stage": "Pre-Series A",
    "teamSize": "10-30名",
    "ceo": "不明",
    "summary": "周産期医療をAIで革新",
    "hiringNeeds": "AIリサーチャー",
    "growthChallenges": "データ収集・研究開発",
    "keywords": [
      "医療AI",
      "周産期",
      "早産",
      "基盤モデル",
      "女性健康"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-037",
    "name": "amoibe",
    "nameEn": "amoibe",
    "sector": "EdTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "新庄 隼人",
    "summary": "AI時代のエンジニア育成を変革",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "大手SIer開拓",
    "keywords": [
      "エンジニア研修",
      "リスキリング",
      "AI人材",
      "OJT",
      "SIer"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "https://amoibe.co.jp/recruit"
  },
  {
    "id": "GV-038",
    "name": "シェルパ・アンド・カンパニー",
    "nameEn": "Cierpa & Company",
    "sector": "ESG / GovTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "杉本 淳",
    "summary": "ESG経営をクラウドで推進",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ESG",
      "サステナビリティ",
      "情報開示",
      "SmartESG"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://cierpa.co.jp/recruit"
  },
  {
    "id": "GV-039",
    "name": "RemitAid",
    "nameEn": "RemitAid",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-040",
    "name": "Luxstay",
    "nameEn": "Luxstay",
    "sector": "Travel Tech",
    "stage": "Seed",
    "teamSize": "30-50名",
    "ceo": "不明",
    "summary": "ベトナムの民泊市場をデジタル化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "ベトナム国内拡大",
    "keywords": [
      "民泊",
      "ベトナム",
      "旅行",
      "ホームステイ"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.linkedin.com/company/luxstay/jobs/"
  },
  {
    "id": "GV-041",
    "name": "SPUN",
    "nameEn": "SPUN",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-042",
    "name": "BCFD Technologies",
    "nameEn": "BCFD Technologies",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-043",
    "name": "Kinish",
    "nameEn": "Kinish",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-044",
    "name": "Plutos ONE",
    "nameEn": "Plutos ONE",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "テクニカルサービスプロバイダー",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-045",
    "name": "Sports For Life (SFL)",
    "nameEn": "Sports For Life",
    "sector": "Sports Tech",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "インドのユーススポーツをスケール",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "インド拡大",
    "keywords": [
      "ユーススポーツ",
      "インド",
      "教育",
      "健康"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-046",
    "name": "AI Mage",
    "nameEn": "AI Mage",
    "sector": "AI / ML",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）AIイメージ生成関連",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "AI",
      "画像生成"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-047",
    "name": "NanoFrontier",
    "nameEn": "NanoFrontier",
    "sector": "DeepTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "井上 誠也",
    "summary": "有機ナノ粒子化技術で材料開発を革新",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [
      "ナノ粒子",
      "有機材料",
      "再沈殿法",
      "東北大学",
      "素材"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-048",
    "name": "Anaguma",
    "nameEn": "Anaguma",
    "sector": "",
    "stage": "Series A",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-049",
    "name": "handpickd",
    "nameEn": "handpickd",
    "sector": "FoodTech",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "インドの生鮮食品ECを変革",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "インド拡大",
    "keywords": [
      "生鮮食品",
      "EC",
      "インド"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-050",
    "name": "ColorSing",
    "nameEn": "ColorSing",
    "sector": "",
    "stage": "Seed",
    "teamSize": "不明",
    "ceo": "不明",
    "summary": "（事業詳細要調査 - カンタさん関連スタートアップ）",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "",
    "keywords": [],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-051",
    "name": "パートナープロップ",
    "nameEn": "Partner Prop",
    "sector": "Sales Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "井上 拓海",
    "summary": "パートナーマーケティングをSaaSで効率化",
    "hiringNeeds": "セールス, CS",
    "growthChallenges": "急成長フェーズ",
    "keywords": [
      "PRM",
      "パートナーマーケティング",
      "代理店管理",
      "SaaS"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.skygate-tech.com/recruit"
  },
  {
    "id": "GV-052",
    "name": "Smart Craft",
    "nameEn": "Smart Craft",
    "sector": "Manufacturing Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "浮部 史也",
    "summary": "製造現場のDXプラットフォーム",
    "hiringNeeds": "エンジニア, セールス",
    "growthChallenges": "製造業市場開拓",
    "keywords": [
      "製造DX",
      "工場",
      "IoT",
      "生産管理",
      "スマホ"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://smartcraft.jp/recruit"
  },
  {
    "id": "GV-053",
    "name": "ユアトレード",
    "nameEn": "YourTrade",
    "sector": "Logistics Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "德永 翔平",
    "summary": "越境ECの返品・在庫を海外で再流通",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "グローバル展開（米国開始済）",
    "keywords": [
      "越境EC",
      "返品",
      "再流通",
      "サーキュラーエコノミー",
      "国際物流"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://thephage.life/recruit"
  },
  {
    "id": "GV-054",
    "name": "スカイゲートテクノロジズ",
    "nameEn": "Skygate Technologies",
    "sector": "DeepTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "粟津 昂規",
    "summary": "防衛テクノロジーで国家安全保障に貢献",
    "hiringNeeds": "エンジニア",
    "growthChallenges": "製品開発・量産化",
    "keywords": [
      "防衛テック",
      "ドローン",
      "ロボティクス",
      "国防"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://ecrowd.co.jp/recruit"
  },
  {
    "id": "GV-055",
    "name": "MiRESSO",
    "nameEn": "MiRESSO",
    "sector": "DeepTech",
    "stage": "Seed",
    "teamSize": "1-10名",
    "ceo": "中道 勝",
    "summary": "核融合の社会実装を鉱物資源供給で支える",
    "hiringNeeds": "CxO, プラントエンジニア, 研究開発",
    "growthChallenges": "パイロットプラント建設（2027年目標）",
    "keywords": [
      "核融合",
      "ベリリウム",
      "低温精製",
      "エネルギー",
      "ディープテック"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-056",
    "name": "ジャパンキャリア",
    "nameEn": "JapanCareer",
    "sector": "HR Tech",
    "stage": "Pre-Seed",
    "teamSize": "1-10名",
    "ceo": "吉田 杏佑",
    "summary": "外国籍人材と国内企業のマッチング",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "外国籍人材基盤構築",
    "keywords": [
      "外国人採用",
      "人材マッチング",
      "共生社会",
      "人手不足"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://www.wantedly.com/companies/japancareer"
  },
  {
    "id": "GV-057",
    "name": "ザ・ファージ",
    "nameEn": "THE PHAGE",
    "sector": "Health Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "德永 翔平",
    "summary": "血糖値の個別化コントロールで人類の健康課題に挑む",
    "hiringNeeds": "研究者, BizDev",
    "growthChallenges": "社会実装の加速",
    "keywords": [
      "血糖値",
      "腸内細菌",
      "ファージ",
      "個別化医療",
      "ヘルスケア"
    ],
    "target_market": "B2C",
    "target_segment": "Consumer",
    "recruitUrl": "https://entaar.com/recruit"
  },
  {
    "id": "GV-058",
    "name": "NOMU",
    "nameEn": "NOMU ENTERPRISE",
    "sector": "FoodTech",
    "stage": "Pre-Seed",
    "teamSize": "1-10名",
    "ceo": "森國 麦",
    "summary": "パーソナライズドリンクで新しい食体験を提供",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "製品開発・市場拡大",
    "keywords": [
      "パーソナライズ",
      "ドリンク",
      "フードテック"
    ],
    "target_market": "B2B",
    "target_segment": "Enterprise",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-059",
    "name": "Entaar",
    "nameEn": "Entaar",
    "sector": "Enterprise DX",
    "stage": "Pre-Series A",
    "teamSize": "1-10名",
    "ceo": "齋藤 大和",
    "summary": "大企業のIT投資をデータとAIで最適化",
    "hiringNeeds": "全ポジション",
    "growthChallenges": "プロダクト開発",
    "keywords": [
      "IT投資",
      "データベース",
      "AI共創",
      "エンタープライズ",
      "DX"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（要調査）"
  },
  {
    "id": "GV-060",
    "name": "FormX",
    "nameEn": "FormX",
    "sector": "FinTech",
    "stage": "Seed",
    "teamSize": "1-10名",
    "ceo": "時田 知典",
    "summary": "上場企業の開示業務をDXで効率化",
    "hiringNeeds": "フロントエンドエンジニア",
    "growthChallenges": "プロダクト開発（2025年8月β版）",
    "keywords": [
      "ディスクロージャー",
      "開示",
      "XBRL",
      "上場企業",
      "IR"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "（情報なし/未公開）"
  },
  {
    "id": "GV-064",
    "name": "匠技研工業",
    "nameEn": "Takumi Giken Kogyo",
    "sector": "Manufacturing Tech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "前田 将太",
    "summary": "町工場の経営DXを匠フォースで実現",
    "hiringNeeds": "エンジニア, セールス",
    "growthChallenges": "製造業市場拡大",
    "keywords": [
      "製造DX",
      "町工場",
      "見積",
      "工場経営",
      "匠フォース"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/takumigiken"
  },
  {
    "id": "GV-065",
    "name": "カイタク",
    "nameEn": "Kaitak",
    "sector": "AI / ML",
    "stage": "Seed",
    "teamSize": "1-10名",
    "ceo": "松木 友範",
    "summary": "AI電話エージェントでコミュニケーションを革新",
    "hiringNeeds": "AIエンジニア",
    "growthChallenges": "プロダクトPMF",
    "keywords": [
      "AI電話",
      "コールセンター",
      "音声AI",
      "エージェント",
      "スパ電"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/kaitak"
  },
  {
    "id": "GV-067",
    "name": "Tensor Energy",
    "nameEn": "Tensor Energy",
    "sector": "CleanTech",
    "stage": "Seed",
    "teamSize": "10-30名",
    "ceo": "堀 菜々 & フィルター・ヴィンセント",
    "summary": "再エネ×蓄電池のオペレーティングシステムを構築",
    "hiringNeeds": "AIエンジニア, BizDev, エネルギー専門家",
    "growthChallenges": "顧客基盤拡大・蓄電池連携の本格化",
    "keywords": [
      "再エネ",
      "蓄電池",
      "FIP",
      "AI発電予測",
      "電力取引",
      "GX",
      "オーケストレーション",
      "Tensor Cloud"
    ],
    "target_market": "B2B",
    "target_segment": "SMB",
    "recruitUrl": "https://www.wantedly.com/companies/TensorEnergy"
  }
];
module.exports = { PORTFOLIO };
